In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Airline.csv')
data.head(10)

airline  avail_seat_km_per_week  incidents_85_99  \
0             Aer Lingus               320906734                2   
1              Aeroflot*              1197672318               76   
2  Aerolineas Argentinas               385803648                6   
3            Aeromexico*               596871813                3   
4             Air Canada              1865253802                2   
5             Air France              3004002661               14   
6             Air India*               869253552                2   
7       Air New Zealand*               710174817                3   
8       Alaska Airlines*               965346773                5   
9               Alitalia               698012498                7   

   fatal_accidents_85_99  fatalities_85_99  incidents_00_14  \
0                      0                 0                0   
1                     14               128                6   
2                      0                 0                1   
3                      1                64                5   
4                      0                 0                2   
5                      4                79                6   
6                      1               329                4   
7                      0                 0                5   
8                      0                 0                5   
9                      2                50                4   

   fatal_accidents_00_14  fatalities_00_14  
0                      0                 0  
1                      1                88  
2                      0                 0  
3                      0                 0  
4                      0                 0  
5                      2               337  
6                      1               158  
7                      1                 7  
8                      1                88  
9                      0                 0

In [3]:
x= data.iloc[:, [2, 3]].values
y = data.iloc[:,4].values
x

array([[ 2,  0],
       [76, 14],
       [ 6,  0],
       [ 3,  1],
       [ 2,  0],
       [14,  4],
       [ 2,  1],
       [ 3,  0],
       [ 5,  0],
       [ 7,  2],
       [ 3,  1],
       [21,  5],
       [ 1,  0],
       [ 5,  3],
       [ 4,  0],
       [ 0,  0],
       [12,  6],
       [ 2,  1],
       [ 3,  1],
       [24, 12],
       [ 8,  3],
       [ 1,  1],
       [25,  5],
       [ 1,  0],
       [10,  3],
       [ 1,  0],
       [ 0,  0],
       [ 4,  1],
       [ 3,  1],
       [ 2,  0],
       [ 7,  1],
       [12,  5],
       [ 3,  2],
       [ 6,  1],
       [ 3,  1],
       [ 8,  3],
       [ 7,  4],
       [ 1,  0],
       [ 5,  3],
       [ 5,  0],
       [ 7,  2],
       [ 2,  2],
       [ 2,  1],
       [ 1,  0],
       [ 2,  1],
       [ 2,  1],
       [ 3,  1],
       [ 8,  3],
       [ 0,  0],
       [ 8,  4],
       [ 8,  3],
       [19,  8],
       [16,  7],
       [ 7,  3],
       [ 1,  0],
       [ 9,  1]], dtype=int64)

In [4]:
y

array([  0, 128,   0,  64,   0,  79, 329,   0,   0,  50,   1, 101,   0,
       323,   0,   0, 535,  16,  47, 407, 282,   4, 167,   0, 260,   0,
         0, 148, 520,   0,   3, 425,  21,   2,  34, 234,  74,   0,  51,
         0, 313,   6, 159,   0,  14, 229,   3,  98,   0, 308,  64, 319,
       224, 171,   0,  82], dtype=int64)

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [6]:
x_train.shape

(44, 2)

In [7]:
x_test.shape

(12, 2)

In [8]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

C:\Users\Shalini\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 6, p = 2)
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [11]:
y_pred = knn.predict(x_test)

In [12]:
from sklearn.metrics import confusion_matrix
confusion_matr= confusion_matrix(y_test, y_pred)
confusion_matr

array([[4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)*100

33.333333333333329

In [14]:
knn = KNeighborsClassifier(n_neighbors = 6, p = 2)
knn.fit(x, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [25]:
x_new=[[5,130],[12,35]]
y_Prednew=knn.predict(x_new)


In [26]:
y_Prednew[]

SyntaxError: invalid syntax (<ipython-input-26-2f3dea3f804a>, line 1)

In [24]:
classes[x_Prednew[1]]

KeyError: 101